//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USVTracking_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaselineManagement
    {
        public string ProjectName { get; set; }
        public string FunctionCode { get; set; }
        public string ResourceName { get; set; }
        public string ResourceType { get; set; }
        public string CurrentVersion { get; set; }
        public string LastestVersion { get; set; }
        public Nullable<decimal> LastRequestID { get; set; }
        public string LastRequestVersion { get; set; }
        public Nullable<System.DateTime> BaselineDate { get; set; }
    }
}
