//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USVTracking_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MappingTrackingAndTimeRecord
    {
        public string Role { get; set; }
        public string TrackingProjectName { get; set; }
        public string TrackingPhaseName { get; set; }
        public string TrackingProcessName { get; set; }
        public string TimeRecordProjectName { get; set; }
        public string TimeRecordPhaseName { get; set; }
        public string TimeRecordProcessName { get; set; }
        public byte DelFlag { get; set; }
    }
}
