//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USVTracking_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressTrackingView
    {
        public string ProjectName { get; set; }
        public string FunctionCode { get; set; }
        public Nullable<decimal> WBSNo { get; set; }
        public Nullable<decimal> LastProgress { get; set; }
    }
}
