//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USVTracking_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMaster
    {
        public string TimeRecordProjectName { get; set; }
        public string ProjectName { get; set; }
        public byte IsScheduled { get; set; }
        public byte DelFlag { get; set; }
    }
}
