//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USVTracking_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestSchedule
    {
        public string ProjectName { get; set; }
        public decimal RequestID { get; set; }
        public string FunctionCode { get; set; }
        public string Description { get; set; }
        public string UserID { get; set; }
        public System.DateTime PlanStart { get; set; }
        public System.DateTime PlanFinish { get; set; }
        public double PlanEffort { get; set; }
        public string RequestType { get; set; }
        public string Status { get; set; }
        public byte DelFlag { get; set; }
    }
}
