using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace USVTracking_MVC.Models
{
    public class SubmitProgessBatchModel
    {
        public string UpdateMethod { get; set; }

        public List<string> ProjectList { get; set; }

        public List<string> WorkingTypeList { get; set; }

        public List<TaskInfo> TaskInfos { get; set; }

        public string Message { get; set; }
    }

    public class PhaseInfo
    {
        public string PhaseID
        { get; set; }

        public string PhaseName
        { get; set; }

        public string Selected { get; set; }
    }

    public class ProcessInformation
    {
        public string ProcessID
        { get; set; }

        public string ProcessName
        { get; set; }

        public byte IsFunctionRequired { get; set; }

        public byte IsProgressRequired { get; set; }

        public byte IsRequestIDRequired { get; set; }

        public byte AutoGenerateDescription { get; set; }

        public string Selected { get; set; }
    }
}