//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USVTracking_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeRecordPhase
    {
        public string TimeRecordPhaseID { get; set; }
        public string TimeRecordPhaseName { get; set; }
        public Nullable<byte> DEV { get; set; }
        public Nullable<byte> COMTOR { get; set; }
        public Nullable<byte> PMO { get; set; }
        public Nullable<byte> OTHERS { get; set; }
    }
}
