//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USVTracking_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingWBSPhaseProcess
    {
        public string ProjectName { get; set; }
        public string Role { get; set; }
        public string TrackingPhaseID { get; set; }
        public string TrackingProcessID { get; set; }
        public Nullable<decimal> WBSNo { get; set; }
        public byte IsFunctionRequired { get; set; }
        public byte IsProgressRequired { get; set; }
        public byte IsRequestIDRequired { get; set; }
        public byte AutoGenerateDescription { get; set; }
        public byte DelFlag { get; set; }
    }
}
