//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USVTracking_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingInfo
    {
        public decimal TrackingNo { get; set; }
        public string UserID { get; set; }
        public System.DateTime Date { get; set; }
        public string WorkingTypeName { get; set; }
        public string ProjectName { get; set; }
        public Nullable<decimal> WBSNo { get; set; }
        public string PhaseName { get; set; }
        public string ProcessName { get; set; }
        public string FunctionCode { get; set; }
        public Nullable<decimal> RequestID { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<decimal> Progress { get; set; }
        public string Description { get; set; }
        public string ApproverID { get; set; }
        public string ApproveComment { get; set; }
        public Nullable<byte> ApprovedFlag { get; set; }
        public Nullable<byte> TimeRecordInsertedFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
    }
}
