//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USVTracking_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public string UserID { get; set; }
        public string Full_Name { get; set; }
        public string InitialName { get; set; }
        public string ADName { get; set; }
        public string Department { get; set; }
        public string Role { get; set; }
        public string TimeRecordPwd { get; set; }
        public byte DelFlag { get; set; }
        public string Email { get; set; }
    }
}
